[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#f05b4f"
backgroundColor = "#090a0c"
secondaryBackgroundColor = "#111317"
textColor = "#f4f1eb"
font = "sans serif"
